name: isupermarket
description: FYP

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1+3
  firebase_core: ^0.5.0+1
  provider: ^4.3.2+2
  intl: ^0.16.1
  flutter_spinkit: ^4.1.2
  firebase_storage: ^5.0.1
  # flutter_svg: ^0.17.4
  stripe_payment: ^1.0.8
  http: ^0.12.2
  flutter_beacon: ^0.3.0
  # flutter_blue: ^0.6.3+1
  flutter_bluetooth_serial: ^0.2.2
  permission_handler: ^4.4.0+hotfix.2
  flutter_credit_card: ^0.1.4
  # http: ^0.11.3+17
  progress_dialog: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Regular.ttf